version: "3.6"
services:

  # Producer (working with sse_api)
  rtp_sse:
    container_name: rtp_sse
    build:
      context: ./rtp_sse
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  # MongoDB
  mongodb_service:
    image: mongo
    container_name: mongo_service
    ports:
      - 27017:27017

  # SSE Tweets Stream
  sse_api:
    image: alexburlacu/rtp-server:faf18x
    container_name: sse_api
    ports:
      - 4000:4000
